# Generated by Django 4.0.3 on 2022-04-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='display_y_n',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='products',
            name='finer_known',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='images_y_n',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='products',
            name='item_no',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='products',
            name='mintage',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='ngc_pop',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='pcgs_pop',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='pop_known',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='total_pop',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='total_units',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='vendor',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='customer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
