# Generated by Django 4.0.3 on 2022-04-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberty', '0002_alter_products_display_y_n_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RenameField(
            model_name='requestlog',
            old_name='timestamp',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='display_y_n',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='display_item',
            field=models.BooleanField(default=False, max_length=120),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='sold',
            field=models.BooleanField(blank=True, default='', max_length=120),
        ),
    ]
