# Generated by Django 4.0.3 on 2022-04-12 19:47

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberty', '0003_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor', models.CharField(max_length=120)),
                ('customer', models.IntegerField()),
                ('description', models.CharField(max_length=120)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grade', models.CharField(max_length=120)),
                ('notes', models.TextField(default='none')),
                ('admin_notes', models.TextField(default='n/a')),
                ('status', models.CharField(max_length=120)),
                ('sold', models.CharField(max_length=120)),
                ('display_y_n', models.CharField(default='no', max_length=120)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='avg_cogs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.TextField(default='Peace'),
        ),
        migrations.AddField(
            model_name='products',
            name='display_y_n',
            field=models.CharField( max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='finer_known',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='highlights',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='images_y_n',
            field=models.CharField(max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='products',
            name='mintage',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='ngc_pop',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='pcgs_pop',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='pop_known',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='products',
            name='total_pop',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='total_units',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='vendor',
            field=models.CharField(max_length=256),
            preserve_default=False,
        ),
    ]
