# Generated by Django 4.0.3 on 2022-04-12 17:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import liberty.models


class Migration(migrations.Migration):

    dependencies = [
        ('liberty', '0003_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='avg_cogs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.TextField(default='Peace'),
        ),
        migrations.AddField(
            model_name='products',
            name='display_y_n',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='products',
            name='finer_known',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='highlights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256), default=liberty.models.highlights_default, size=None),
        ),
        migrations.AddField(
            model_name='products',
            name='images_y_n',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='products',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='products',
            name='mintage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='ngc_pop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='pcgs_pop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='pop_known',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='products',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='products',
            name='total_pop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='total_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='vendor',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='products',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='products',
            name='on_hold_till',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='test',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
