# Generated by Django 4.0.3 on 2022-04-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberty', '0004_products_avg_cogs_products_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor', models.CharField(max_length=120)),
                ('customer', models.IntegerField()),
                ('description', models.CharField(max_length=120)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grade', models.CharField(max_length=120)),
                ('notes', models.TextField()),
                ('admin_notes', models.TextField()),
                ('status', models.CharField(max_length=120)),
                ('sold', models.CharField(max_length=120)),
                ('display_y_n', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='display_y_n',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='products',
            name='images_y_n',
            field=models.CharField(max_length=256),
        ),
    ]
