# Generated by Django 4.0.3 on 2022-04-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberty', '0004_requestlog_products_avg_cogs_products_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='admin_notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='display_y_n',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='notes',
            field=models.TextField(),
        ),
    ]
