# Generated by Django 4.0.3 on 2022-04-13 17:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('liberty', '0006_alter_products_display_y_n_alter_products_images_y_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='admin_notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='advisor',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='customer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='description',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='display_y_n',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='grade',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='sold',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='status',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liberty.category')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liberty.category'),
        ),
    ]
